(function(w,d){'use strict';
/* V13 Scales UI — iframe-safe renderer. Curriculum data is read-only; only selected normalized items enter Lesson/Homework. */
var NS=w.VIOLIN_AI_CURRICULUM=w.VIOLIN_AI_CURRICULUM||{};
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
function read(k,f){try{var x=JSON.parse(w.localStorage.getItem(k)||'null');return x==null?f:x}catch(e){return f}}
function agenda(){var x=read('VIOLIN_AI_AGENDA_V10',{});return Array.isArray(x.students)?x.students:[]}
function sid(s){return String(s&&(s.id??s.studentId??s.uid)??'')}
function student(doc){var a=agenda(),body=(doc.body&&doc.body.innerText)||'',heads=[].slice.call(doc.querySelectorAll('h1,h2')),head=heads.length?(heads[0].textContent||'').trim():'';for(var i=0;i<a.length;i++){var s=a[i],n=String(s.name||s.studentName||'').trim();if(n&&(body.indexOf(n)>=0||head.indexOf(n)>=0))return s}var lm=body.match(/Level\s+(\d+)/i),tm=body.match(/Term\s+(\d+)/i);return lm?{name:(head.split(/[·•—-]/)[1]||'Student').trim(),level:+lm[1],term:tm?+tm[1]:1}:null}
function data(lv,tm){var D=w.VIOLIN_SCALE_CURRICULUM_V1;if(!D)return null;try{return typeof D.getTerm==='function'?D.getTerm(lv,tm):(D.levels?.[lv]?.[tm]||D.terms?.[lv]?.[tm]||D[lv]?.[tm]||null)}catch(e){return null}}
function items(lv,tm){var C=w.VIOLIN_AI_CURRICULUM,c=[];try{if(C&&C.scales&&typeof C.scales.list==='function'){c=C.scales.list(lv,tm);if(Array.isArray(c)&&c.length)return c}}catch(e){}var x=data(lv,tm);if(!x)return[];[['major','Major Scales'],['minor','Minor Scales'],['arpeggios','Tonic Arpeggios'],['dominant7','Dominant 7th'],['diminished7','Diminished 7th'],['chromatic','Chromatic Scales'],['doubleStops','Double Stops'],['oneString','One-String Scales']].forEach(function(f){var v=x[f[0]];(Array.isArray(v)?v:[v]).forEach(function(z){if(z)c.push({id:'scale-'+lv+'-'+tm+'-'+c.length,curriculum:'scales',category:f[1],title:String(z),level:lv,term:tm,requirements:{tempo:x.tempo,octaves:x.octaves,bowing:x.bowing,articulation:x.articulation,rhythmicGroups:x.rhythm,accents:x.accents,dynamics:x.dynamics,positions:x.positions},objective:x.objective,mastery:x.mastery,source:'scale-curriculum-data.js'})})});return c}
function norm(x,lv,tm){return NS.controller&&NS.controller.normalize?NS.controller.normalize('scales',x,{level:lv,term:tm,source:x.source||'curriculum'}):x}
function css(doc){if(doc.getElementById('v13scalesuicss'))return;var s=doc.createElement('style');s.id='v13scalesuicss';s.textContent='.v13-scale-wrap{margin:12px 0;padding:12px;border:1px solid #dfd4ff;border-radius:14px;background:#faf8ff;color:#24344c}.v13-scale-head h3{margin:0 0 3px;font-size:18px}.v13-scale-sub{font-size:12px;color:#687487;margin-bottom:8px}.v13-scale-cat{margin:7px 0 5px;padding:7px 9px;border:1px solid #e4e0ef;border-radius:9px;background:#fff;font-size:12px;font-weight:900;display:flex;justify-content:space-between;cursor:pointer}.v13-scale-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.v13-scale-card{display:flex;align-items:flex-start;gap:7px;padding:7px 8px;border:1px solid #e6e8ee;border-radius:9px;background:#fff;min-height:38px;box-sizing:border-box;cursor:pointer}.v13-scale-card input{width:17px;height:17px;min-width:17px;margin:1px 0 0}.v13-scale-card b{font-size:12px}.v13-scale-meta{display:flex;gap:3px;flex-wrap:wrap;margin-top:2px}.v13-scale-pill{font-size:8px;padding:2px 4px;border-radius:999px;background:#f1f3f7;color:#59667a}.v13-scale-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.v13-scale-actions button{border:0;border-radius:8px;padding:7px 10px;font-weight:800;cursor:pointer;font-size:11px}.v13-scale-actions .lesson{background:#24344c;color:#fff}.v13-scale-actions .home{background:#64c6a3;color:#12372c}.v13-scale-actions .clear{background:#eef1f5;color:#24344c}@media(max-width:900px){.v13-scale-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.v13-scale-grid{grid-template-columns:1fr}}';doc.head.appendChild(s)}
function render(host,it,s,frame){var doc=host.ownerDocument;css(doc);var groups={};it.forEach(function(x,i){(groups[x.category]||(groups[x.category]=[])).push({x:x,i:i})});var h='<div class="v13-scale-wrap"><div class="v13-scale-head"><h3>🎼 Curriculum Scales</h3><div class="v13-scale-sub">Level '+esc(s.level)+' · Term '+esc(s.term)+' · Select scales for today.</div></div>';Object.keys(groups).forEach(function(cat,ci){var id='v13cat'+ci;h+='<div class="v13-scale-cat" data-cat="'+id+'">'+esc(cat)+' <span>▼</span></div><div class="v13-scale-grid" data-grid="'+id+'">';groups[cat].forEach(function(z){var r=z.x.requirements||{};h+='<label class="v13-scale-card"><input type="checkbox" data-i="'+z.i+'"><span><b>'+esc(z.x.title)+'</b><div class="v13-scale-meta">'+(r.octaves?'<span class="v13-scale-pill">'+esc(r.octaves)+'</span>':'')+(r.tempo?'<span class="v13-scale-pill">'+esc(r.tempo)+'</span>':'')+'</div></span></label>'});h+='</div>'});h+='<div class="v13-scale-actions"><button class="lesson" data-a="lesson">🎓 Add to Lesson</button><button class="home" data-a="home">🏠 Add to Homework</button><button class="clear" data-a="clear">Clear</button></div></div>';host.innerHTML=h;host.querySelectorAll('.v13-scale-cat').forEach(function(b){b.onclick=function(){var g=host.querySelector('[data-grid="'+b.dataset.cat+'"]'),closed=g.style.display==='none';g.style.display=closed?'grid':'none';b.querySelector('span').textContent=closed?'▼':'▶'}});function chosen(){return it.filter(function(x,i){var q=host.querySelector('[data-i="'+i+'"]');return q&&q.checked}).map(function(x){return norm(x,s.level,s.term)})}host.querySelector('[data-a="clear"]').onclick=function(){host.querySelectorAll('input').forEach(function(q){q.checked=false})};function save(kind){var x=chosen();if(!x.length)return alert('Select at least one scale.');var p={studentId:sid(s),studentName:s.name||s.studentName||'',level:s.level,term:s.term,kind:kind,curriculum:'scales',items:x,createdAt:new Date().toISOString()};if(NS.controller&&NS.controller.select)NS.controller.select(p);else localStorage.setItem('VIOLIN_AI_CURRICULUM_SELECTION_V2',JSON.stringify(p));if(kind==='lesson')frame.src='./lesson.html?studentId='+encodeURIComponent(p.studentId)+'&v=v13-master-lesson-6';else alert('Scales added to Homework.')};host.querySelector('[data-a="lesson"]').onclick=function(){save('lesson')};host.querySelector('[data-a="home"]').onclick=function(){save('homework')}}
function isScales(doc){return [].slice.call(doc.querySelectorAll('h1,h2')).some(function(x){return /^🎵?\s*SCALES\s*[·•—-]/i.test((x.textContent||'').trim())})}
function mount(){try{var frame=d.getElementById('app');if(!frame)return;var doc=frame.contentDocument;if(!doc||!doc.body||!isScales(doc))return;var s=student(doc);if(!s)return;var lv=Number(String(s.level||1).match(/\d+/)?.[0]||1),tm=Number(String(s.term||1).match(/\d+/)?.[0]||1),it=items(lv,tm);if(!it.length)return;var host=doc.getElementById('v13scalesuimount');if(!host){host=doc.createElement('section');host.id='v13scalesuimount';var add=[].slice.call(doc.querySelectorAll('button')).find(function(b){return /add\s+scales/i.test((b.textContent||''))});if(add&&add.parentElement&&add.parentElement.parentElement)add.parentElement.parentElement.appendChild(host);else(doc.querySelector('.wrap')||doc.body).appendChild(host)}var key=lv+'|'+tm+'|'+sid(s)+'|'+it.length;if(host.dataset.key!==key){host.dataset.key=key;render(host,it,{id:s.id||s.studentId||s.uid,name:s.name||s.studentName,level:lv,term:tm},frame)}}catch(e){console.log('V13 SCALES UI',e)}}
NS.scalesUI={version:'4.0',render:render};w.VIOLIN_AI_CURRICULUM=NS;w.addEventListener('load',function(){setTimeout(mount,300);setTimeout(mount,1000);setTimeout(mount,2500)});setInterval(mount,500);
})(window,document);