import { registerTeacherUnitCard } from './registry.js';

const card = (input) => registerTeacherUnitCard(input);

const common = {
  difficultyBand: 'CORE',
  status: 'PROVISIONAL'
};

// V1 real Teacher Unit Cards. Content is deliberately kept at the validated
// curriculum level; exact exercise numbering is not invented where sources
// support only a study family/pool.

export const L1T1 = card({
  ...common,
  level: 1,
  term: 1,
  technicalIntent: 'Establish stable posture, basic coordination, first-position geography, reading, and controlled basic bowing.',
  prerequisites: ['Instrument setup', 'Stable standing/sitting posture', 'Basic open-string control'],
  scalesLink: ['Open strings', 'First-position finger patterns', 'Basic one-octave scale work'],
  pureTechnical: ['Open-string long détaché / controlled bow distribution', 'Ševčík Op. 1 Part 1 No. 1', 'Schradieck Book 1 No. 1', 'Basic string crossings', '2/4-note slurs'],
  etudes: ['Suzuki Etude', 'Suzuki Perpetual Motion A/D with 16th-note variation', 'Wohlfahrt Op. 38 No. 40', 'Applebaum selected elementary study', 'Doflein selected elementary study'],
  repertoire: ['Suzuki early-level repertoire', 'Wohlfahrt elementary character piece', 'Doflein elementary repertoire selection', 'Eastman Level 1 repertoire selection', 'Short contrasting first-position piece'],
  technicalDomains: ['posture', 'coordination', 'bow control', 'first position', 'reading'], musicalDomains: ['steady pulse', 'basic dynamics', 'articulation', 'phrase awareness'],
  teacherDecisionLogic: ['Observe posture and setup', 'Identify coordination or bow-control deficit', 'Select the corresponding pure-technical intervention', 'Transfer to an etude and short repertoire piece'],
  readinessCriteria: ['Stable setup throughout playing', 'Consistent first-position intonation in simple material', 'Controlled basic bow strokes', 'Reliable reading of simple notation'], nextTermDependency: 'Retain first-position security while expanding bow patterns, finger changes, and string-crossing coordination.'
});

export const L1T2 = card({ ...common, level: 1, term: 2, technicalIntent: 'Consolidate first-position security and introduce more coordinated slurring, finger changes, and string crossings.', prerequisites: ['L1T1 setup and basic bow control', 'Basic first-position reading'], scalesLink: ['First-position major/minor patterns', 'One-octave scales with simple articulations'], pureTechnical: ['Ševčík Op. 1 Part 1 Nos. 2–4', 'Schradieck Book 1 continuation', 'Wohlfahrt Op. 38 selected first-position pattern', 'Hooked/slurred bow patterns', 'First-position finger changes + string crossing'], etudes: ['Wohlfahrt Op. 38 selected first-position study', 'Suzuki Perpetual Motion variation work', 'Applebaum selected study', 'Doflein selected study', 'Whistler selected elementary study'], repertoire: ['Huber selected elementary piece', 'Kuchler selected elementary piece', 'Rieding selected elementary piece', 'Seitz selected elementary piece', 'Suzuki contrasting repertoire selection'], technicalDomains: ['first position', 'finger changes', 'string crossing', 'slurring', 'bow distribution'], musicalDomains: ['rhythm', 'dynamics', 'articulation', 'short-form phrasing'], teacherDecisionLogic: ['Check L1T1 stability', 'Locate breakdown in finger/bow coordination', 'Isolate the pattern', 'Reintegrate into etude and repertoire'], readinessCriteria: ['Reliable first-position finger patterns', 'Controlled hooked/slurred bowing', 'Clean basic string crossings', 'Stable rhythm while coordinating both hands'], nextTermDependency: 'Prepare the student for controlled shifting and introductory articulation work in Level 2.' });

export const L2T1 = card({ ...common, level: 2, term: 1, technicalIntent: 'Introduce controlled movement beyond first position and the first double-stop, harmonic, and articulated-bow foundations.', prerequisites: ['Secure first position', 'Reliable basic string crossing', 'Basic slurred bow control'], scalesLink: ['First-position scales', 'Introductory shift patterns toward third position'], pureTechnical: ['1st→3rd shift', 'Natural harmonics', 'First-position introductory double stops', 'Colle preparation', 'Martele preparation'], etudes: ['Kayser selected study', 'Polo selected double-stop study', 'Trott selected double-stop study', 'Wohlfahrt selected study', 'Whistler selected study'], repertoire: ['Huber selected concerto movement', 'Kuchler selected concerto movement', 'Portnoff selected student concerto', 'Rieding selected concerto movement', 'Seitz selected concerto movement'], technicalDomains: ['shifting', 'harmonics', 'double stops', 'colle', 'martele'], musicalDomains: ['tone production', 'articulation', 'dynamic contrast', 'phrase direction'], teacherDecisionLogic: ['Confirm first-position baseline', 'Introduce one new technical variable at a time', 'Use pure technical work before etude application', 'Test transfer in concerto-style repertoire'], readinessCriteria: ['Controlled first→third shifts', 'Stable natural harmonics', 'Clean introductory double stops', 'Emerging colle and martele control'], nextTermDependency: 'Expand third-position security, double-stop patterns, harmonics, and articulated bow strokes.' });

export const L2T2 = card({ ...common, level: 2, term: 2, technicalIntent: 'Expand third-position movement and consolidate introductory double stops, harmonics, colle, and martele.', prerequisites: ['L2T1 first→third shift', 'Basic double-stop and harmonic control'], scalesLink: ['One/two-octave scales with third-position work', 'Shift-preparation patterns'], pureTechnical: ['Expanded 1st→3rd shifting', 'Natural harmonics across adjacent strings', 'First-position double-stop patterns', 'Colle with string changes', 'Martele + controlled crossing'], etudes: ['Kayser selected study', 'Polo selected double-stop study', 'Trott selected double-stop study', 'Wohlfahrt selected study', 'Whistler selected study'], repertoire: ['Portnoff selected concerto', 'Rieding selected concerto', 'Seitz selected concerto', 'Kuchler selected concerto', 'Suzuki contrasting character piece'], technicalDomains: ['third position', 'shifting', 'double stops', 'harmonics', 'articulated bowing'], musicalDomains: ['tone', 'phrasing', 'articulation', 'dynamic shaping'], teacherDecisionLogic: ['Test shift consistency', 'Separate left-hand and bow-stroke faults', 'Use targeted intervention', 'Retest in repertoire at controlled tempo'], readinessCriteria: ['Reliable first↔third movement', 'Improved double-stop stability', 'Natural harmonics without collapse of tone', 'Controlled colle/martele with crossings'], nextTermDependency: 'Prepare second/fourth/fifth-position introduction, vibrato, and more advanced bow articulation.' });

export const L3T1 = card({ ...common, level: 3, term: 1, technicalIntent: 'Build secure first/third-position proficiency while introducing second-position patterns, vibrato, trills, and flexible bow articulation.', prerequisites: ['Secure L2 shifting', 'Basic double-stop control', 'Stable articulated bow strokes'], scalesLink: ['Two-octave position-based scales', 'Third-position patterns'], pureTechnical: ['1st→3rd shift prepared', '2nd-position patterns', 'Basic vibrato', 'Trill preparation', 'Up-bow staccato preparation'], etudes: ['Kayser selected study', 'Mazas selected study', 'Polo selected study', 'Sitt selected study', 'Trott selected study'], repertoire: ['Barber selected piece', 'Dancla selected piece', 'Fiocco Allegro', 'Handel selected sonata movement', 'Vivaldi selected movement'], technicalDomains: ['shifting', 'positions', 'vibrato', 'trills', 'up-bow staccato'], musicalDomains: ['tone colour', 'dynamics', 'phrasing', 'style awareness'], teacherDecisionLogic: ['Assess first/third-position reliability', 'Introduce second position only when the baseline is stable', 'Develop vibrato separately from shifting', 'Transfer articulation into repertoire'], readinessCriteria: ['Secure first and third positions', 'Emerging second-position control', 'Usable basic vibrato', 'Clean preparation for trill and up-bow staccato'], nextTermDependency: 'Extend position vocabulary and coordinate vibrato, chords, trills, and faster bow articulation.' });

export const L3T2 = card({ ...common, level: 3, term: 2, technicalIntent: 'Extend position work through fourth/fifth positions and integrate vibrato, chord preparation, trills, and up-bow staccato.', prerequisites: ['L3T1 position and vibrato foundations', 'Stable first↔third shifting'], scalesLink: ['Position-based two/three-octave preparation', 'Shift mapping'], pureTechnical: ['3rd→5th shift', '4th-position patterns', 'Continuous vibrato through position change', '2→3-note chord preparation', 'Advanced trill preparation'], etudes: ['Kayser selected study', 'Mazas selected study', 'Polo selected study', 'Sitt selected study', 'Trott selected study'], repertoire: ['Mlynarski selected piece', 'Portnoff selected piece', 'Severn selected piece', 'Vivaldi selected movement', 'Handel selected sonata movement'], technicalDomains: ['position changes', 'vibrato', 'chords', 'trills', 'up-bow staccato'], musicalDomains: ['phrasing', 'dynamic range', 'articulation', 'Baroque/Classical style'], teacherDecisionLogic: ['Verify L3T1 position security', 'Introduce fifth-position movement in short cells', 'Maintain vibrato through the shift', 'Use repertoire as the integration test'], readinessCriteria: ['Controlled fourth-position patterns', 'Reliable third→fifth movement', 'Continuous vibrato through simple shifts', 'Clean chord/trill preparation'], nextTermDependency: 'Move into first five positions, extension/half position, three-octave work, and continuous vibrato.' });

export const L4T1 = card({ ...common, level: 4, term: 1, technicalIntent: 'Establish the first five positions, extension/half position, continuous vibrato, and the first integrated three-octave position-transition work.', prerequisites: ['L3T2 position vocabulary', 'Stable vibrato', 'Reliable introductory chords and articulation'], scalesLink: ['Three-octave scales and arpeggio preparation', 'Position-transition drills'], pureTechnical: ['1→3→5 shift', 'Extension/half-position', 'Continuous vibrato + shift', 'Isolated 3-octave position-transition drills (not scale work)', 'Introduction to thirds/sixths'], etudes: ['Kayser No. 4', 'Kayser No. 13', 'Kreutzer No. 5', 'Sitt No. 6', 'Trott No. 5'], repertoire: ['Accolay Violin Concerto No. 1 in A minor', 'Kreisler Sicilienne and Rigaudon', 'Haydn Violin Concerto in G major', 'Tartini Fugue — CHALLENGE', 'Bach Violin Concerto in A minor — READINESS'], technicalDomains: ['first five positions', 'shifting', 'extensions', 'vibrato', 'introductory double stops'], musicalDomains: ['Baroque style', 'Classical style', 'Romantic character', 'articulation', 'phrasing'], teacherDecisionLogic: ['Check position map', 'Diagnose shift/extension/vibrato fault', 'Choose one targeted technical intervention', 'Apply through the selected etude', 'Use repertoire as the readiness test'], readinessCriteria: ['Reliable first five positions', 'Secure simple extensions/half position', 'Continuous vibrato through basic shifts', 'Emerging thirds/sixths without destabilising intonation'], nextTermDependency: 'Increase shift speed, integrate double stops with movement, and develop a broader articulated-bow vocabulary.' });

export const L4T2 = card({ ...common, level: 4, term: 2, technicalIntent: 'Increase shift speed and integrate double stops, continuous vibrato, extended slurs, and emerging advanced articulated bow strokes.', prerequisites: ['L4T1 first-five-position security', 'Three-octave transition preparation', 'Introductory thirds/sixths'], scalesLink: ['Three-octave scales/arpeggio sequences', 'Double-stop scale introduction'], pureTechnical: ['Rapid 1→3→5 shifting', 'Double stops + shifts', 'Continuous vibrato', 'Martele→staccato→emerging spiccato', 'Extended slur + crossing'], etudes: ['Kayser No. 4', 'Kayser No. 13', 'Kreutzer No. 5', 'Sitt No. 7', 'Trott No. 9'], repertoire: ['Monti Czardas', 'Handel selected sonata movement', 'Kreisler contrasting character work', 'Weber selected movement', 'Dancla contrasting virtuoso work — CHALLENGE'], technicalDomains: ['rapid shifting', 'double stops', 'vibrato', 'spiccato preparation', 'slurring'], musicalDomains: ['character', 'articulation', 'dynamic contrast', 'style transition', 'phrasing'], teacherDecisionLogic: ['Test L4T1 dependencies at faster tempo', 'Identify whether failure is left-hand, bow, or coordination', 'Isolate the deficit', 'Reapply in etude', 'Confirm transfer in repertoire'], readinessCriteria: ['Faster 1→3→5 shifts without collapse', 'Stable double stops during simple movement', 'Continuous vibrato', 'Controlled transition from martele/staccato toward spiccato', 'Extended slurs with clean crossings'], nextTermDependency: 'Prepare all-position mapping, ricochet, longer up-bow staccato, and connected double-stop work for Level 5.' });

export const L1_L4_TKTL_V1 = Object.freeze([L1T1, L1T2, L2T1, L2T2, L3T1, L3T2, L4T1, L4T2]);

// L5-L6 are implemented in the next TKTL module and re-exported here so the
// canonical V1 card module exposes the complete currently implemented set.
export * from './cards-l5-l6.js';
